version: '3'
services:
  spring-mysqldbi:
    image: tayeblagha/affectationbackend
    environment:
      - MYSQL_HOST=mysqldbi
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - mysqldbi
    networks:
      - spring-mysql

  mysqldbi:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=AffectationDatabase
    networks:
      - spring-mysql

networks:
  spring-mysql:
    driver: bridge

